config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/pages/services', to: 'pages#services', as: 'services'
  get '/pages/proteger', to: 'pages#proteger'
  get '/pages/formations', to: 'pages#formations'
  get '/pages/support', to: 'pages#support'
  get '/pages/contact', to: 'pages#contact'
  get '/pages/conditions', to: 'pages#conditions'
  get '/pages/articleun', to: 'pages#articleun'
  get '/pages/articledeux', to: 'pages#articledeux'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  #GET
  def home
  end

  #GET
  def services
  end
  #GET
  def proteger
  end
  #GET
  def formations
  end
  #GET
  def support
  end

  def contact
  end

  def conditions  
  end

  def articleun
  end
  
  def articledeux
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer Section -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="footer-block footer-contact"> 
                    <%= link_to image_tag('theme-logo.png', alt:'securitykeys', class:'logosecu'), root_path %>
                    <ul>
                        <li><i class="fa fa-phone" aria-hidden="true"></i><span><a href="tel: +33 6 27 92 23 93">+33 6 27 92 23 93</a></span></li>
                        <li><i class="fa fa-envelope"></i><span><a href="mailto: contact@securitykeys.eu">contact@securitykeys.eu</a></span></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="footer-block blog-link">
                    <h4>Derniers articles</h4>
                    <ul>
                        <li>
                            <%= link_to "Internet c'est dangereux, avec SecurityKeys.eu c'est mieux et c'est plus sûre.", pages_articleun_path %>
                            <span>
                                <i class="far fa-calendar-alt"></i>
                                </i> June 16, 2017
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Bottom Footer Section -->
    <div class="bottom-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <div class="bottom-footer-left">
                        <p>© 2019 Security Keys | All Rights Reserved. | Mentions légales</p>
                        <%= link_to "CONDITIONS DE VENTE", pages_conditions_path(:class => 'conditionsstyle') %>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <div class="bottom-footer-right">
                        <div class="social-link">
                            <ul>
                                <li><a href="#" title="Facebook" target="_blank"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#" title="Twitter" target="_blank"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#" title="Google +" target="_blank"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li>
                                <li><a href="#" title="Pinterest" target="_blank"><i class="fab fa-pinterest-p" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Top Header Section PARTIE BLEUEEEEEEEE-->
<div class="upper-header">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-8 col-xs-12">
                <div class="upper-header-info">
                    <ul>
                        <li><a href="tel: +33 6 27 92 23 93"><i class="fa fa-phone" aria-hidden="true"></i> &nbsp; +33 6 27 92 23 93</a></li>
                        <li><a href="mailto: contact@securitykeys.eu"><i class="far fa-envelope" aria-hidden="true"></i> &nbsp; contact@securitykeys.eu</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="social-link">
                    <ul>
                        <li><a href="#" title="Facebook" target="_blank"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                        <li><a href="#" title="Twitter" target="_blank"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#" title="Google +" target="_blank"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#" title="Pinterest" target="_blank"><i class="fab fa-pinterest-p" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Bottom Header Section PARTIE BLANCHEEEEEE-->
<div class="container">
    <div class="row">
        <!-- logo part -->
        <div class="col-md-3 col-sm-12 col-xs-12">
            <div class="logo-holder">
                <%= link_to image_tag('theme-logo.png', alt:'securitykeys', class:'logosecu'), root_path %>
            </div>
        </div>
            <div class="cssmenu">
                <ul>
                    <li><%= link_to('Services',services_path) %></li>
                    <li><%= link_to('Protéger',pages_proteger_path) %></li>
                    <li><%= link_to('Formations',pages_formations_path) %></li>
                    <li><%= link_to('Support',pages_support_path) %></li>
                    <li><%= link_to('Contact',pages_contact_path) %></li>
                </ul>
            </div>
        </div>
     </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecurityKeys</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.theme.default.min.css">

    <script src="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/owl.carousel.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/articledeux.html.erb
<div class="page-title">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <h2>Article</h2>
            </div>
        </div>
    </div>
</div>
<!-- Recent Update Section -->
<div class="blog-details">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <h3 class="title">Internet c'est dangereux, avec Security Keys c'est mieux et c'est plus sure.</h3>
                <p class="date">17 Juillet 2018</p>
                <%= image_tag('image2.jpg', class: 'img-responsive articlebandeau') %>
                <p>
                    Votre monde tourne autour d'internet et de votre ordinateur, ce média qui trace le futur, a facilité la vies et les relations entre les individus mais a beaucoup de faiblesses et de fragilités. Du petit hacker qui bloque votre bureau d'ordinateur à l'employé malveillant qui détruit votre comptabilité ou votre facturation. Que pouvez vous faire contre le petit génie qui manipule l'informatique comme un artiste et qui récolte vos données personnelles, vos photos ou simplement vos données de carte bleue pour les revendre ou simplement les diffuser sans votre accord.
                </p>
                <blockquote>
                    Rencontrez nous et nous vous formerons aux manipulations a réaliser, aux protections simples que vous devez connaître afin de vous protéger.
                </blockquote>
                <p>
                    La sécurité est devenue cruciale pour que votre outil reste opérationnel et sans risque. Faites sécuriser votre ordinateur avec Security Keys. Connectez vous sur SecurityKeys.eu dès maintenant. Nous vous proposons de vous inscrire sur Facebook et l'heureux chanceux pourra gagne un déjeuner a l'atelier des chefs donc n'attendez pas inscrivez vous et likez notre page internet. Merci de nous contacter pour plus d'informations.
                </p>

            </div>
        </div>
    </div>
</div>

<!-- Recent Update Section -->
<section class="recent-update innerpage-recent-update bg-grey">
    <div class="container">
        <div class="title">
            <h2>Autres articles</h2>
        </div>

        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="recent-update-block">
                    <div class="recent-update-img">
                        <a href="blog-details.html">
                        <%= link_to image_tag('image1.jpg', class: 'img-responsive'), pages_articleun_path %>
                        <div class="recent-update-date">
                            <div class="date">16 </div>
                            <div class="month">Juin</div>
                            <div class="year">2018</div>
                        </div>
                    </div>
                    <div class="recent-update-content">
                        <h3>Internet c'est dangereux, avec SecurityKeys.eu c'est mieux et c'est plus sûre.</h3>
                        <p>Votre monde tourne autour de votre ordinateur et d'internet, ce média qui trace le futur, a facilité la vie et les relations entre les individus mais a beaucoup de faiblesses et de fragilités.</p>
                        <%= link_to 'Lire la suite', pages_articleun_path, :class => "more viewmore-4" %>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="recent-update-block">
                    <div class="recent-update-img">
                        <%= link_to image_tag('image2.jpg', class: 'img-responsive'), pages_articledeux_path %>
                        <div class="recent-update-date">
                            <div class="date">16 </div>
                            <div class="month">Juin</div>
                            <div class="year">2018</div>
                        </div>
                    </div>
                    <div class="recent-update-content">
                        <h3>Proposez a vos amis de nous connaître. Partagez et protégez les des attaques par virus.</h3>
                        <p>Vous avez envie de partager et d'apprendre à vous protéger des virus, chevaux de Troie, Ramsomware, et autres attaques qui peuvent vous faire tout perdre.</p>
                        <%= link_to 'Lire la suite', pages_articledeux_path, :class => "more viewmore-4" %>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>

app/views/pages/articleun.html.erb
<div class="page-title">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <h2>Article</h2>
            </div>
        </div>
    </div>
</div>
<!-- Recent Update Section -->
<div class="blog-details">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <h3 class="title">Internet c'est dangereux, avec Security Keys c'est mieux et c'est plus sure.</h3>
                <p class="date">17 Juillet 2018</p>
                <%= image_tag('image1.jpg', class: 'img-responsive articlebandeau') %>
                <p>
                    Votre monde tourne autour d'internet et de votre ordinateur, ce média qui trace le futur, a facilité la vies et les relations entre les individus mais a beaucoup de faiblesses et de fragilités. Du petit hacker qui bloque votre bureau d'ordinateur à l'employé malveillant qui détruit votre comptabilité ou votre facturation. Que pouvez vous faire contre le petit génie qui manipule l'informatique comme un artiste et qui récolte vos données personnelles, vos photos ou simplement vos données de carte bleue pour les revendre ou simplement les diffuser sans votre accord.
                </p>
                <blockquote>
                    Rencontrez nous et nous vous formerons aux manipulations a réaliser, aux protections simples que vous devez connaître afin de vous protéger.
                </blockquote>
                <p>
                    La sécurité est devenue cruciale pour que votre outil reste opérationnel et sans risque. Faites sécuriser votre ordinateur avec Security Keys. Connectez vous sur SecurityKeys.eu dès maintenant. Nous vous proposons de vous inscrire sur Facebook et l'heureux chanceux pourra gagne un déjeuner a l'atelier des chefs donc n'attendez pas inscrivez vous et likez notre page internet. Merci de nous contacter pour plus d'informations.
                </p>

            </div>
        </div>
    </div>
</div>

<!-- Recent Update Section -->
<section class="recent-update innerpage-recent-update bg-grey">
    <div class="container">
        <div class="title">
            <h2>Autres articles</h2>
        </div>

        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="recent-update-block">
                    <div class="recent-update-img">
                        <a href="blog-details.html">
                        <%= link_to image_tag('image1.jpg', class: 'img-responsive'), pages_articleun_path %>
                        <div class="recent-update-date">
                            <div class="date">16 </div>
                            <div class="month">Juin</div>
                            <div class="year">2018</div>
                        </div>
                    </div>
                    <div class="recent-update-content">
                        <h3>Internet c'est dangereux, avec SecurityKeys.eu c'est mieux et c'est plus sûre.</h3>
                        <p>Votre monde tourne autour de votre ordinateur et d'internet, ce média qui trace le futur, a facilité la vie et les relations entre les individus mais a beaucoup de faiblesses et de fragilités.</p>
                        <%= link_to 'Lire la suite', pages_articleun_path, :class => "more viewmore-4" %>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="recent-update-block">
                    <div class="recent-update-img">
                        <%= link_to image_tag('image2.jpg', class: 'img-responsive'), pages_articledeux_path %>
                        <div class="recent-update-date">
                            <div class="date">16 </div>
                            <div class="month">Juin</div>
                            <div class="year">2018</div>
                        </div>
                    </div>
                    <div class="recent-update-content">
                        <h3>Proposez a vos amis de nous connaître. Partagez et protégez les des attaques par virus.</h3>
                        <p>Vous avez envie de partager et d'apprendre à vous protéger des virus, chevaux de Troie, Ramsomware, et autres attaques qui peuvent vous faire tout perdre.</p>
                        <%= link_to 'Lire la suite', pages_articledeux_path, :class => "more viewmore-4" %>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>

app/views/pages/contact.html.erb
<!-- Page title Section CONTACT-->
<div class="page-title">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <h2>Contact</h2>
    </div>
</div>
<!-- Contact Section ADRESSE ET PHONE -->
<section class="contact-details">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="contact-address">
                    <h3 class="title">Contact Security Keys</h3>
                    <ul>
                        <a href="tel: +33 6 27 92 23 93"><i class="fa fa-phone" aria-hidden="true"></i> &nbsp; +33 6 27 92 23 93</a></br></br>
                        <a href="mailto: contact@securitykeys.eu"><i class="far fa-envelope" aria-hidden="true"></i> &nbsp; contact@securitykeys.eu</a>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="contact-form">
                    <h3 class="title">Contact Formulaire</h3>
                    <form name="form" class="form" method="post" action="#" enctype="multipart/form-data">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12">
                                    <input class="form-control" name="name" type="text" placeholder="Nom de famille" />
                                </div>
                                <div class="col-md-6 col-sm-12 col-xs-12">
                                    <input class="form-control" name="prenom" type="text" placeholder="Prénom" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12">
                                    <input class="form-control" name="email" type="email" placeholder="Email" />
                                </div>
                                <div class="col-md-6 col-sm-12 col-xs-12">
                                    <input class="form-control" name="pays" type="text" placeholder="Pays" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <textarea class="form-control" name="message" placeholder="Message"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input name="submit" class="more viewmore-3" type="submit" value="Envoyer le message" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/pages/formations.html.erb
<div class="page-title">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <h2>FORMATIONS</h2>
    </div>
</div>
<section class="cms-contain">
    <div class="container">
        <div class="row">
            <div class="col-md-7 col-sm-12 col-xs-12">
                <h5>Nos interventions font l'objet d'une préparation détaillée.</h5>
                <p>Ainsi, elles correspondent réellement à vos besoins en tenant compte de l'existant et des contraintes propres à votre entreprise et à votre environnement. Nous vous offrons des formations sur-mesure en fonction de vos besoins spécifiques.</p>
                <ul>
                    <li>Formation logiciels Word Excel PowerPoint Access 4D CRM Oracle</li>
                    <li>Formation Réseaux</li>
                    <li>Formation Systèmes</li>
                    <li>Formation Sécurité Informatique</li>
                </ul>
                <p>Nous faisons des formations intra et inter entreprises merci de nous contacter pour plus d'informations.</p>
            </div>
            <div class="col-md-5 col-sm-12 col-xs-12">
                <div class="about-img">
                    <%= image_tag('photoserv1.jpg', class: 'img_formation') %>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="page-title">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <h2>DÉLÉGATION DE PERSONNEL</h2>
        <P>Nous mettons à votre disposition des profils expérimentés et adaptés à votre structure et vos besoins techniques.</P>
    </div>
</div>
<section class="cms-contain">
    <div class="container">
        <div class="row">
            <div class="col-md-7 col-sm-12 col-xs-12">
                <h5>Pourquoi faire appel au service de délégation de personnel ?</h5>
                <ul>
                    <li>Pour une continuité de service</li>
                    <li>Pour renforcer une équipe informatique lors d’un projet</li>
                    <li>Pour obtenir l'expertise d'un consultant</li>
                    <li>Pour se concentrer sur les activités stratégiques</li>
                    <li>Pour un personnel qualifié tout en optimisant vos charges opérationnelles et RHopérationnelles et RH</li>
                    <li>Pour une meilleure flexibilité</li>
                </ul>
            </div>
            <div class="col-md-5 col-sm-12 col-xs-12">
                <div class="about-img">
                    <%= image_tag('photoserv2.jpg') %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/pages/proteger.html.erb
<!-- Page title Section-->
<div class="page-title">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <h2>PROTÉGER</h2>
        </div>
    </div>
</div>
<!-- feature-service Section -->
<section class="feature-service">
    <div class="container">
        <div class="title">
            <h2>Sécuriser, Protéger, Former à la sécurité informatique.</h2>
            <p class="text">Retravailler rapidement après une attaque ou une perte de données</p>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="service-block proteger">
                    <div class="service-img">
                        <%= link_to image_tag('photoserv1.jpg', class: 'img-responsive'), services_path %>
                    </div>
                    <div class="service-content ">
                        <h3><a href="service-details.html">PROTÉGER VOS SYSTÈMES, COMMENT ÇA MARCHE ...</a></h3>
                        <p>Vous aider à comprendre comment vous pouvez sécuriser vos données, <br> vos fichiers, vos photos, <br>vos informations clients et les données confidentielles, voilà l'objectif <br>de notre société et le service <br>que nous comptons vous apporter.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="service-block proteger">
                    <div class="service-img">
                        <%= link_to image_tag('photoserv2.jpg', class: 'img-responsive'), services_path %>
                    </div>
                    <div class="service-content">
                        <h3><a href="service-details.html">VOUS ÊTES ATTAQUÉ, QUE FAIRE, COMMENT RÉAGIR ...</a></h3>
                        <p>Comment se défendre si on vous vole <br>vos données bancaires <br>ou votre identité ? <br>Qui prévenir ? <br>Quand prévenir ? <br>Quels sont vos recours ? <br>Comment faire pour redémarrer <br>votre activité ?</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="service-block proteger">
                    <div class="service-img">
                        <%= link_to image_tag('photoserv3.jpg', class: 'img-responsive'), services_path %>
                    </div>
                    <div class="service-content">
                        <h3><a href="service-details.html">COMMENT NOUS INTERVENONS :</a></h3>
                        <p class="intervention">- Par une analyse de votre demande d'aide <br>- Par une série de conseils de protection. <br>- Par des actions de protection immédiate <br>- Par une prise de main à distance par un ingénieur compétent <br>- Nous nous déplaçons chez vous pour essayer de récupérer vos données, protéger votre système ... <br>- Nous vous aidons a tout ré-installer et à redémarrer le plus rapidement possible.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="viewmore">
            <%= link_to 'En savoir plus', services_path, :class => "more viewmore-1" %>
        </div>
    </div>
</section>

app/views/pages/support.html.erb
<!-- Page title Section-->
<div class="page-title">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <h2>Support</h2>
            </div>
        </div>
    </div>
</div>
<section class="feature-service">
    <div class="container">
        <div class="title">
            <p>Sur indication de nos ingénieurs veuillez télécharger certains logiciels et suivez strictement nos indications.</p>
            <p class="text">Merci de nous contacter pour plus d'informations.</p>
        </div>
		<div class="row">
		    <div class="col">
		        <div class="service-content">
		            <h3><a href="http://www.mscit.fr/prog/TeamViewer_Setup.exe">TeamVeaver</a></h3>
		            <p>Logiciel de prise de contrôle a distance de votre ordinateur.</p>
		        </div>
		    </div>
		    <div class="col">
		        <div class="service-content">
		            <h3><a href="http://www.mscit.fr/prog/VNC-Server-6.2.1-Windows.exe">UltraVNC</a></h3>
		            <p>Logiciel de prise de contrôle Open Source.</p>
		        </div>
		    </div>
		</div>
	</div>
</section>